export const REPORT_CREATE_START = `REPORT_CREATE_START`;
export const REPORT_CREATE_SUCCESS = `REPORT_CREATE_SUCCESS`;
export const REPORT_CREATE_ERROR = `REPORT_CREATE_ERROR`;

export const REPORT_GET_START = `REPORT_GET_START`;
export const REPORT_GET_SUCCESS = `REPORT_GET_SUCCESS`;
export const REPORT_GET_ERROR = `REPORT_GET_ERROR`;

export const REPORT_UPDATE_START = `REPORT_UPDATE_START`;
export const REPORT_UPDATE_SUCCESS = `REPORT_UPDATE_SUCCESS`;
export const REPORT_UPDATE_ERROR = `REPORT_UPDATE_ERROR`;

export const REPORT_DESTROY_START = `REPORT_DESTROY_START`;
export const REPORT_DESTROY_SUCCESS = `REPORT_DESTROY_SUCCESS`;
export const REPORT_DESTROY_ERROR = `REPORT_DESTROY_ERROR`;

export const REPORT_FIND_START = `REPORT_FIND_START`;
export const REPORT_FIND_SUCCESS = `REPORT_FIND_SUCCESS`;
export const REPORT_FIND_ERROR = `REPORT_FIND_ERROR`;

export const REPORT_EXPORT_START = `REPORT_EXPORT_START`;
export const REPORT_EXPORT_SUCCESS = `REPORT_EXPORT_SUCCESS`;
export const REPORT_EXPORT_ERROR = `REPORT_EXPORT_ERROR`;

export const REPORT_ERROR_MESSAGE_CLEAR = `REPORT_ERROR_MESSAGE_CLEAR`;

export const REPORT_TABLE_ROW_SELECTION = `REPORT_TABLE_ROW_SELECTION`;
export const REPORT_TABLE_ROW_CLICK = `REPORT_TABLE_ROW_CLICK`;
export const REPORT_FILTER_CHANGE = `REPORT_FILTER_CHANGE`;
