export const LEDGER_PUBLIC_GET_START = `LEDGER_PUBLIC_GET_START`;
export const LEDGER_PUBLIC_GET_SUCCESS = `LEDGER_PUBLIC_GET_SUCCESS`;
export const LEDGER_PUBLIC_GET_ERROR = `LEDGER_PUBLIC_GET_ERROR`;
