export const SHIFT_CREATE_START = `SHIFT_CREATE_START`;
export const SHIFT_CREATE_SUCCESS = `SHIFT_CREATE_SUCCESS`;
export const SHIFT_CREATE_ERROR = `SHIFT_CREATE_ERROR`;

export const SHIFT_GET_START = `SHIFT_GET_START`;
export const SHIFT_GET_SUCCESS = `SHIFT_GET_SUCCESS`;
export const SHIFT_GET_ERROR = `SHIFT_GET_ERROR`;

export const SHIFT_UPDATE_START = `SHIFT_UPDATE_START`;
export const SHIFT_UPDATE_SUCCESS = `SHIFT_UPDATE_SUCCESS`;
export const SHIFT_UPDATE_ERROR = `SHIFT_UPDATE_ERROR`;

export const SHIFT_DESTROY_START = `SHIFT_DESTROY_START`;
export const SHIFT_DESTROY_SUCCESS = `SHIFT_DESTROY_SUCCESS`;
export const SHIFT_DESTROY_ERROR = `SHIFT_DESTROY_ERROR`;

export const SHIFT_FIND_START = `SHIFT_FIND_START`;
export const SHIFT_FIND_SUCCESS = `SHIFT_FIND_SUCCESS`;
export const SHIFT_FIND_ERROR = `SHIFT_FIND_ERROR`;

export const SHIFT_EXPORT_START = `SHIFT_EXPORT_START`;
export const SHIFT_EXPORT_SUCCESS = `SHIFT_EXPORT_SUCCESS`;
export const SHIFT_EXPORT_ERROR = `SHIFT_EXPORT_ERROR`;

export const SHIFT_ERROR_MESSAGE_CLEAR = `ERROR_MESSAGE_CLEAR`;

export const SHIFT_TABLE_ROW_SELECTION = `TABLE_ROW_SELECTION`;
export const SHIFT_TABLE_ROW_CLICK = `TABLE_ROW_CLICK`;

