export const LEDGER_CREATE_START = `LEDGER_CREATE_START`;
export const LEDGER_CREATE_SUCCESS = `LEDGER_CREATE_SUCCESS`;
export const LEDGER_CREATE_ERROR = `LEDGER_CREATE_ERROR`;

export const LEDGER_GET_START = `LEDGER_GET_START`;
export const LEDGER_GET_SUCCESS = `LEDGER_GET_SUCCESS`;
export const LEDGER_GET_ERROR = `LEDGER_GET_ERROR`;

export const LEDGER_UPDATE_START = `LEDGER_UPDATE_START`;
export const LEDGER_UPDATE_SUCCESS = `LEDGER_UPDATE_SUCCESS`;
export const LEDGER_UPDATE_ERROR = `LEDGER_UPDATE_ERROR`;

export const LEDGER_DESTROY_START = `LEDGER_DESTROY_START`;
export const LEDGER_DESTROY_SUCCESS = `LEDGER_DESTROY_SUCCESS`;
export const LEDGER_DESTROY_ERROR = `LEDGER_DESTROY_ERROR`;

export const LEDGER_FIND_START = `LEDGER_FIND_START`;
export const LEDGER_FIND_SUCCESS = `LEDGER_FIND_SUCCESS`;
export const LEDGER_FIND_ERROR = `LEDGER_FIND_ERROR`;

export const LEDGER_EXPORT_START = `LEDGER_EXPORT_START`;
export const LEDGER_EXPORT_SUCCESS = `LEDGER_EXPORT_SUCCESS`;
export const LEDGER_EXPORT_ERROR = `LEDGER_EXPORT_ERROR`;

export const LEDGER_ERROR_MESSAGE_CLEAR = `ERROR_MESSAGE_CLEAR`;

export const LEDGER_TABLE_ROW_SELECTION = `LEDGER_TABLE_ROW_SELECTION`;
export const LEDGER_TABLE_ROW_CLICK = `LEDGER_TABLE_ROW_CLICK`;

export const LEDGER_SAUNA_CHANGE = `LEDGER_SAUNA_CHANGE`;
export const LEDGER_MASSEUR_CHANGE = `LEDGER_MASSEUR_CHANGE`;

export const LEDGER_SERVICE_SELECT = `LEDGER_SERVICE_SELECT`;
export const LEDGER_SERVICE_ITEMS_CHANGE = `LEDGER_SERVICE_ITEMS_CHANGE`;
export const LEDGER_SERVICE_ITEM_ADD_CLICK = `LEDGER_SERVICE_ITEM_ADD_CLICK`;
export const LEDGER_SERVICE_ITEM_REMOVE_CLICK = `LEDGER_SERVICE_ITEM_REMOVE_CLICK`;
export const LEDGER_LINK_CHANGE = `LEDGER_LINK_CHANGE`;
export const LEDGER_CLEAR_CHANGE = `LEDGER_CLEAR_CHANGE`;
export const LEDGER_DISCOUNT_CHANGE = `LEDGER_DISCOUNT_CHANGE`;
export const LEDGER_PAYMENT_METHOD_CHANGE = `LEDGER_PAYMENT_METHOD_CHANGE`;
