export const STAFF_CREATE_START = `STAFF_CREATE_START`;
export const STAFF_CREATE_SUCCESS = `STAFF_CREATE_SUCCESS`;
export const STAFF_CREATE_ERROR = `STAFF_CREATE_ERROR`;

export const STAFF_GET_START = `STAFF_GET_START`;
export const STAFF_GET_SUCCESS = `STAFF_GET_SUCCESS`;
export const STAFF_GET_ERROR = `STAFF_GET_ERROR`;

export const STAFF_UPDATE_START = `STAFF_UPDATE_START`;
export const STAFF_UPDATE_SUCCESS = `STAFF_UPDATE_SUCCESS`;
export const STAFF_UPDATE_ERROR = `STAFF_UPDATE_ERROR`;

export const STAFF_DESTROY_START = `STAFF_DESTROY_START`;
export const STAFF_DESTROY_SUCCESS = `STAFF_DESTROY_SUCCESS`;
export const STAFF_DESTROY_ERROR = `STAFF_DESTROY_ERROR`;

export const STAFF_FIND_START = `STAFF_FIND_START`;
export const STAFF_FIND_SUCCESS = `STAFF_FIND_SUCCESS`;
export const STAFF_FIND_ERROR = `STAFF_FIND_ERROR`;

export const STAFF_EXPORT_START = `STAFF_EXPORT_START`;
export const STAFF_EXPORT_SUCCESS = `STAFF_EXPORT_SUCCESS`;
export const STAFF_EXPORT_ERROR = `STAFF_EXPORT_ERROR`;

export const STAFF_ERROR_MESSAGE_CLEAR = `ERROR_MESSAGE_CLEAR`;

export const STAFF_TABLE_ROW_SELECTION = `TABLE_ROW_SELECTION`;
export const STAFF_TABLE_ROW_CLICK = `TABLE_ROW_CLICK`;

