export const USER_CREATE_START = `USER_CREATE_START`;
export const USER_CREATE_SUCCESS = `USER_CREATE_SUCCESS`;
export const USER_CREATE_ERROR = `USER_CREATE_ERROR`;

export const USER_GET_START = `USER_GET_START`;
export const USER_GET_SUCCESS = `USER_GET_SUCCESS`;
export const USER_GET_ERROR = `USER_GET_ERROR`;

export const USER_UPDATE_START = `USER_UPDATE_START`;
export const USER_UPDATE_SUCCESS = `USER_UPDATE_SUCCESS`;
export const USER_UPDATE_ERROR = `USER_UPDATE_ERROR`;

export const USER_DESTROY_START = `USER_DESTROY_START`;
export const USER_DESTROY_SUCCESS = `USER_DESTROY_SUCCESS`;
export const USER_DESTROY_ERROR = `USER_DESTROY_ERROR`;

export const USER_FIND_START = `USER_FIND_START`;
export const USER_FIND_SUCCESS = `USER_FIND_SUCCESS`;
export const USER_FIND_ERROR = `USER_FIND_ERROR`;

export const USER_EXPORT_START = `USER_EXPORT_START`;
export const USER_EXPORT_SUCCESS = `USER_EXPORT_SUCCESS`;
export const USER_EXPORT_ERROR = `USER_EXPORT_ERROR`;

export const USER_ERROR_MESSAGE_CLEAR = `USER_ERROR_MESSAGE_CLEAR`;

export const USER_TABLE_ROW_SELECTION = `USER_TABLE_ROW_SELECTION`;
export const USER_TABLE_ROW_CLICK = `USER_TABLE_ROW_CLICK`;

