export const SERVICE_CREATE_START = `SERVICE_CREATE_START`;
export const SERVICE_CREATE_SUCCESS = `SERVICE_CREATE_SUCCESS`;
export const SERVICE_CREATE_ERROR = `SERVICE_CREATE_ERROR`;

export const SERVICE_GET_START = `SERVICE_GET_START`;
export const SERVICE_GET_SUCCESS = `SERVICE_GET_SUCCESS`;
export const SERVICE_GET_ERROR = `SERVICE_GET_ERROR`;

export const SERVICE_UPDATE_START = `SERVICE_UPDATE_START`;
export const SERVICE_UPDATE_SUCCESS = `SERVICE_UPDATE_SUCCESS`;
export const SERVICE_UPDATE_ERROR = `SERVICE_UPDATE_ERROR`;

export const SERVICE_DESTROY_START = `SERVICE_DESTROY_START`;
export const SERVICE_DESTROY_SUCCESS = `SERVICE_DESTROY_SUCCESS`;
export const SERVICE_DESTROY_ERROR = `SERVICE_DESTROY_ERROR`;

export const SERVICE_FIND_START = `SERVICE_FIND_START`;
export const SERVICE_FIND_SUCCESS = `SERVICE_FIND_SUCCESS`;
export const SERVICE_FIND_ERROR = `SERVICE_FIND_ERROR`;

export const SERVICE_EXPORT_START = `SERVICE_EXPORT_START`;
export const SERVICE_EXPORT_SUCCESS = `SERVICE_EXPORT_SUCCESS`;
export const SERVICE_EXPORT_ERROR = `SERVICE_EXPORT_ERROR`;

export const SERVICE_ERROR_MESSAGE_CLEAR = `ERROR_MESSAGE_CLEAR`;

export const SERVICE_TABLE_ROW_SELECTION = `TABLE_ROW_SELECTION`;
export const SERVICE_TABLE_ROW_CLICK = `TABLE_ROW_CLICK`;

