export const NOTE_CREATE_START = `NOTE_CREATE_START`;
export const NOTE_CREATE_SUCCESS = `NOTE_CREATE_SUCCESS`;
export const NOTE_CREATE_ERROR = `NOTE_CREATE_ERROR`;

export const NOTE_GET_START = `NOTE_GET_START`;
export const NOTE_GET_SUCCESS = `NOTE_GET_SUCCESS`;
export const NOTE_GET_ERROR = `NOTE_GET_ERROR`;

export const NOTE_READMORE_START = `NOTE_READMORE_START`;
export const NOTE_READMORE_SUCCESS = `NOTE_READMORE_SUCCESS`;
export const NOTE_READMORE_ERROR = `NOTE_READMORE_ERROR`;

export const NOTE_UPDATE_START = `NOTE_UPDATE_START`;
export const NOTE_UPDATE_SUCCESS = `NOTE_UPDATE_SUCCESS`;
export const NOTE_UPDATE_ERROR = `NOTE_UPDATE_ERROR`;

export const NOTE_DESTROY_START = `NOTE_DESTROY_START`;
export const NOTE_DESTROY_SUCCESS = `NOTE_DESTROY_SUCCESS`;
export const NOTE_DESTROY_ERROR = `NOTE_DESTROY_ERROR`;

export const NOTE_FIND_START = `NOTE_FIND_START`;
export const NOTE_FIND_SUCCESS = `NOTE_FIND_SUCCESS`;
export const NOTE_FIND_ERROR = `NOTE_FIND_ERROR`;

export const NOTE_EXPORT_START = `NOTE_EXPORT_START`;
export const NOTE_EXPORT_SUCCESS = `NOTE_EXPORT_SUCCESS`;
export const NOTE_EXPORT_ERROR = `NOTE_EXPORT_ERROR`;

export const NOTE_ERROR_MESSAGE_CLEAR = `ERROR_MESSAGE_CLEAR`;

export const NOTE_TABLE_ROW_SELECTION = `TABLE_ROW_SELECTION`;
export const NOTE_TABLE_ROW_CLICK = `TABLE_ROW_CLICK`;

export const NOTE_TOGGLE_VISIBLE = `NOTE_TOGGLE_VISIBLE`;
