export const BRANCH_CREATE_START = `BRANCH_CREATE_START`;
export const BRANCH_CREATE_SUCCESS = `BRANCH_CREATE_SUCCESS`;
export const BRANCH_CREATE_ERROR = `BRANCH_CREATE_ERROR`;

export const BRANCH_GET_START = `BRANCH_GET_START`;
export const BRANCH_GET_SUCCESS = `BRANCH_GET_SUCCESS`;
export const BRANCH_GET_ERROR = `BRANCH_GET_ERROR`;

export const BRANCH_UPDATE_START = `BRANCH_UPDATE_START`;
export const BRANCH_UPDATE_SUCCESS = `BRANCH_UPDATE_SUCCESS`;
export const BRANCH_UPDATE_ERROR = `BRANCH_UPDATE_ERROR`;

export const BRANCH_DESTROY_START = `BRANCH_DESTROY_START`;
export const BRANCH_DESTROY_SUCCESS = `BRANCH_DESTROY_SUCCESS`;
export const BRANCH_DESTROY_ERROR = `BRANCH_DESTROY_ERROR`;

export const BRANCH_FIND_START = `BRANCH_FIND_START`;
export const BRANCH_FIND_SUCCESS = `BRANCH_FIND_SUCCESS`;
export const BRANCH_FIND_ERROR = `BRANCH_FIND_ERROR`;

export const BRANCH_EXPORT_START = `BRANCH_EXPORT_START`;
export const BRANCH_EXPORT_SUCCESS = `BRANCH_EXPORT_SUCCESS`;
export const BRANCH_EXPORT_ERROR = `BRANCH_EXPORT_ERROR`;

export const BRANCH_ERROR_MESSAGE_CLEAR = `ERROR_MESSAGE_CLEAR`;

export const BRANCH_TABLE_ROW_SELECTION = `TABLE_ROW_SELECTION`;
export const BRANCH_TABLE_ROW_CLICK = `TABLE_ROW_CLICK`;

